# FOSElasticaBundle (Elastic Search)
fos_elastica:
  clients:
    default: { host: localhost, port: 9200 }
  indexes:

    app:
      client: default
      settings:
        index:
          analysis:
            analyzer:
              custom_search_analyzer:
                type: custom
                tokenizer: standard
                filter   : [standard, lowercase, asciifolding]
              custom_index_analyzer:
                type: custom
                tokenizer: standard
                filter   : [standard, lowercase, asciifolding, custom_filter]
            filter:
              custom_filter:
                type: edgeNGram
                side: front
                min_gram: 1
                max_gram: 20
      types:
        city:
          mappings:
            names:
              type : object
              properties :
                name :
                  search_analyzer: custom_search_analyzer
                  index_analyzer: custom_index_analyzer
                  type: string
            postcode:
              type: string
            note:
              type: integer
              index: not_analyzed
            country:
              type: object
              properties:
                code:
                  type: string
          persistence:
            driver: orm
            model: AppBundle\Entity\City
            finder: ~
            provider: ~
            listener: ~
            repository: AppBundle\Entity\CityRepository