# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.registration:
        class: AppBundle\Form\User\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\User\ProfileType
        tags:
          - { name: form.type, alias: app_user_profile }

    app.form.stop:
        class: AppBundle\Form\Stop\StopType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: app_stop_edit }

    app.form.trip_search:
        class: AppBundle\Form\Trip\TripSearchType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: app_trip_search }

    app.form.datePicker:
        class: AppBundle\Form\Type\DatePickerType
        tags:
          - { name: form.type, alias: datePicker }

    app.form.daysOfWeek:
        class: AppBundle\Form\Type\DaysOfWeekType
        tags:
          - { name: form.type, alias: daysOfWeek }

    app.slug:
        class: AppBundle\Utils\Slug
