# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.registration:
        class: AppBundle\Form\User\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\User\ProfileType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
          - { name: form.type, alias: app_user_profile }

    app.form.stop:
        class: AppBundle\Form\Stop\StopType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: app_stop_edit }

    app.form.flow.trip:
        class: AppBundle\Form\Trip\TripFlow
        parent: craue.form.flow

    app.form.trip_search:
        class: AppBundle\Form\Trip\TripSearchType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: app_trip_search }

    app.form.datePicker:
        class: AppBundle\Form\Type\DatePickerType
        tags:
          - { name: form.type, alias: datePicker }

    app.form.daysOfWeek:
        class: AppBundle\Form\Type\DaysOfWeekType
        tags:
          - { name: form.type, alias: daysOfWeek }

    app.slug:
        class: AppBundle\Utils\Slug

    app.mail_manager:
        class: AppBundle\Utils\MailManager
        arguments: ["@mailer", "@twig","%contact_email%","%from_email%","%from_name%"]

    app.user_email_confirmation:
        class: AppBundle\EventListener\EmailConfirmationListener
        arguments: ["@fos_user.user_manager","@fos_user.util.token_generator.default","@session", "@router","@app.mail_manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.user_person:
        class: AppBundle\EventListener\UserPersonListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }
