#=== Config for Sonata Admin ===
#===============================

services:

  # Crud services

  sonata.admin.user:
    class: AppBundle\Admin\UserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Admin", label: "Users" }
    arguments:
      - ~
      - AppBundle\Entity\User
      - ~
    calls:
      - [ setTranslationDomain, [AppBundle]]

  sonata.admin.trip:
      class: AppBundle\Admin\TripAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "Admin", label: "Trips" }
      arguments:
        - ~
        - AppBundle\Entity\Trip
        - ~
      calls:
        - [ setTranslationDomain, [AppBundle]]

sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts:   [admin]

    sonata.block.service.text:

# Dashboard blocks

sonata_admin:
  title: Admin Vadrouille
  title_logo: bundles/app/img/vadrouille-covoiturage-on-black.png
  options:
    title_mode: single_image
  security:
    handler: sonata.admin.security.handler.role

  assets:
    stylesheets:
    # Defaults:
      - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
      - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
      - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
      - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
      - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
      - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
      - bundles/sonataadmin/vendor/select2/select2.css
      - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
      - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
      - bundles/sonataadmin/css/styles.css
      - bundles/sonataadmin/css/layout.css
    # Override
      - bundles/app/css/sonataadmin/styles.css

  dashboard:
    blocks:
      -
        position: left
        type: sonata.admin.block.admin_list
      -
        position: right
        type: sonata.block.service.text
        settings:
          content: >
            <h3 class="box-title">Rafraîchir les trajets</h3>
            <p>Cliques pour rafraîchir le timestamp de prochain départ des trajets :</p>
            <p>
            <a class="btn btn-default" href="/app_dev.php/admin/covoiturage/refresh">Rafraîchir (dev)!</a>
            <a class="btn btn-primary" href="/admin/covoiturage/refresh">Rafraîchir !</a>
            </p>

sonata_doctrine_orm_admin:
  templates:
    form:
      - bootstrap_3_layout.html.twig

