#=== Config for Sonata Admin ===
#===============================



services:

  # Crud services

  sonata.admin.user:
    class: AppBundle\Admin\UserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Admin", label: "Users" }
    arguments:
      - ~
      - AppBundle\Entity\User
      - ~
    calls:
      - [ setTranslationDomain, [AppBundle]]

  sonata.admin.trip:
      class: AppBundle\Admin\TripAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "Admin", label: "Trips" }
      arguments:
        - ~
        - AppBundle\Entity\Trip
        - ~
      calls:
        - [ setTranslationDomain, [AppBundle]]

sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts:   [admin]

    sonata.block.service.text:

# Dashboard blocks

sonata_admin:
  dashboard:
    blocks:
      -
        position: left
        type: sonata.admin.block.admin_list
      -
        position: right
        type: sonata.block.service.text
        settings:
          content: >
            <h3 class="box-title">Rafraîchir les trajets</h3>
            <p>Cliques pour rafraîchir le timestamp de prochain départ des trajets :</p>
            <p>
            <a class="btn btn-default" href="/app_dev.php/admin/covoiturage/refresh">Rafraîchir (dev)!</a>
            <a class="btn btn-primary" href="/admin/covoiturage/refresh">Rafraîchir !</a>
            </p>

