AppBundle\Entity\User:
    properties:
    # Your custom fields in your user entity, here is an example of fullName
       gender:
            - NotBlank:
                message: user.gender.blank
                groups: [ "AppRegistration", "AppProfile" ]
       firstName:
            - NotBlank:
                message: user.firstName.blank
                groups: [ "AppRegistration", "AppProfile" ]
            - Length:
                min: 2
                minMessage: user.firstName.short
                max: 255
                maxMessage: user.firstName.long
                groups: [ "AppRegistration", "AppProfile" ]
       lastName:
            - NotBlank:
                message: user.lastName.blank
                groups: [ "AppRegistration", "AppProfile" ]
            - Length:
                min: 2
                minMessage: user.lastName.short
                max: 255
                maxMessage: user.lastName.long
                groups: [ "AppRegistration", "AppProfile" ]
       phone:
           - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                message: user.phone.invalid
                groups: [ "AppRegistration", "AppProfile" ]


# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: emailCanonical
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "AppRegistration", "AppProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "AppRegistration", "AppProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "AppRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "AppRegistration", "AppProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "AppRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 6
                minMessage: fos_user.password.blank
                groups: [ "AppRegistration", "AppProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "AppRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "AppRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "AppRegistration", "AppProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "AppRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "AppRegistration", "AppProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "AppRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 6
                minMessage: fos_user.password.blank
                groups: [ "AppRegistration", "AppProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "AppRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "AppRegistration" ]